# The service providing the commit statuses to GitHub.
status = [
  "buildbot/buildbot-build-script"
]

# Allow 30 mins for builds.
timeout_sec = 1800

# Have bors delete auto-merged branches
delete_merged_branches = true
